name: nextflow-master
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - openjdk=17
  - nextflow
  - curl
  - pigz
  - fastp
  - fastqc
  - star=2.7.11b
  - cutadapt
  - tqdm
  - samtools
  - bedtools
  - matplotlib
  - pandas
  - numpy
  - scipy
