name: nextflow-master
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - openjdk=17
  - nextflow=25.10.4
  - curl
  - pigz
  - fastp
  - fastqc
  - multiqc
  - star=2.7.11b
  - bwa
  - cutadapt
  - tqdm
  - samtools
  - r-base
  - r-archr=1.0.3
  - r-biocmanager
  - bioconductor-bsgenome.hsapiens.ucsc.hg19
  - bioconductor-bsgenome.hsapiens.ucsc.hg38
  - bioconductor-bsgenome.mmusculus.ucsc.mm10
  - bedtools
  - matplotlib
  - pandas
  - biopython
  - numpy
  - scipy
  # SHARE_seq_pipeline utils.py (sgRNA share_seq_step2_rename_fastq.py / match_gRNA.py)
  - python-levenshtein
  - seaborn
  - pip:
    - regex
